config/routes.rb
Rails.application.routes.draw do
  get 'errors/exception_occured'

	get '/analytics', to: "analytics#index"
	get 'messages/received'
	get 'messages/sent'
	get 'messages/archived'
	get 'dashboard/show_dashboard'
	get 'dashboard/contact_us'
	get 'dashboard/contact_us_submit'
	get 'dashboard/public_urls'
	get 'summary/Lamule_community'
	get 'summary/ExperienceLevel'
	get 'summary/history'
	get 'summary/policy'
	get 'summary/partner'
	get 'summary/termsconditions'
	get 'summary/howitworks'
	get 'summary/origin'
	get 'summary/about_us'
	get 'users/index_facebook'
	get 'users/index_not_facebook'
	get 'users/signUp_email_page'
	post 'users/verify_uid'
	get 'transections/payment'
	get 'driver_verifications/profile_verification'
	get 'driver_verifications/personal_information'
	post 'transfer_requests/make_transfer_request'


	get 'driver_verifications/email_token_generator'
	
	post 'transfers/transfer_funds'
	get 'notifications/booking_notifications'
	match '/twitter', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-blog-post', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-shark-tank', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-inspirational', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-add', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-boosted-post', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/instagram', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/edm', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/press', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/news', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/photopostcards', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/unirideshare', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/alpinerideshare', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/surfrideshare', :to => 'dashboard#public_urls', :via => [:get, :post]
	


	devise_for :users,
						 controllers: {
								 sessions: "users/sessions",
								 registrations: "users/registrations",
								 passwords: "users/passwords",
								 omniauth_callbacks: "users/omniauth_callbacks"
						 }
	root :to => "dashboard#index"
	resources :users

	get "/fill_phone", to: "phone_number#fill_phone"
	get "/verify_phone_number", to: "phone_number#verify_phone_number"
	get "/confirm_phone", to: "phone_number#confirm_phone"
	get "/confirmation_phone", to: "phone_number#confirmation_phone"
	get "/complete_registration_proccess", to: "users#complete_registration_proccess"
	get "/send_verify_email", to: "users#send_verify_email"
	get "/verified_the_email", to: "users#verified_the_email"
	get "/profile/preferences", to: "preferences#edit"
	get "/profile/notifications", to: "notifications#index"
	get "/profile/social_sharing", to: "users#social_sharing"
	get '/profile/credit_card', to: "users#credit_card"
	post '/transfers/revert_transfer/:id', to: "transfers#revert_transfer", as: "revert_transfer"
	patch '/profile/update_credit_card_info', to: "users#update_credit_card_info"
	post "/profile/disconnect_facebook", to: "users#disconnect_facebook"
	
	get "/offer-seats/1", to: "rides#offer_seat_1"
	get "/:id/offer-seats/2", to: "rides#offer_seat_2"
	resources :users, only: [] do
		member do
			get :public_profile
			get :payments_history
		end
		collection do
			post :send_direct_message
		end	
	end
	
	resources :driver_verifications, only: [:index] do
		collection do
			get :steps
			post :verify_profile
			post :verify_email_pin_code
			post :verify_phone_pin_code
			get  :check_email_verified
			get  :check_phone_verified
			post :verify_personal_info
			get :finished
		end	
	end
		
	resources :bookings do
		collection do
			get :past_bookings
		end
		member do
			get :accept
			get :reject
		end
	end
	resources :profile, only: [] do
		collection do
			get :general
			get :photo
			get :verifications
			get :address
			patch :update_general_info
			patch :update_address
			post :verify_email_phone
		end
		member do
			patch :upload_photo
		end
	end
	resources :unsubscribes, only: [] do
		collection do
			get 'account'
			delete 'delete_account'
		end
	end
	resources :cars, only: [:index, :new, :create, :edit, :update, :destroy] do
		member do
			patch :upload_image
		end
	end

	resources :transections, only: [:refund] do
		member do
			get :refund
		end
	end
	
	resources :car_makers, only: [] do
		resources :car_models, only: [:index]
	end
	resources :preferences, only: [:update]
	resources :notifications, only: [] do
		collection do
			patch :update_user_notifications
			patch :update_fackbook_notifications
		end
	end
	resources :rides, only: [:index, :destroy, :edit, :update, :show, :create] do
		resources :locations, only: [:destroy]
		collection do
			post :create_offer_1
			get :rides_info
			post :make_legs
			post :make_schedule
			get :previous_rides
			get :archive_rides
			get :range_rides
		end
		member do
			get :share_on_facebook
			patch :create_offer_2
			get :publication
			patch :set_car
			get :contact_to_the_driver
			put :add_seat
			put :delete_seat
			post :duplicate_ride
			get :visitors
			patch :archive
			get :successfully_posted_rides
		end
	end

	resources :message_threads, only: [:show, :destroy] do
		resources :messages, only: [:create]
		member do
			post :set_archive
		end
	end

	resources :ratings, only: [:new, :create, :edit, :update, :destroy] do
		collection do
			get :hints
			get :search_user
			get :rate_user
			get :received
			get :given
		end
	end

	resources :email_alerts, only: [:index, :new, :create, :destroy] do
		collection do
			get :send_email
			get :email_cron
		end
		member do
		   get :update_travel_date
		end
	end

	resource :mail_chimp, only: [:create]

	match '/404', to: 'errors#exception_occured', via: :all
	match '/422', to: 'errors#exception_occured', via: :all
	match '/500', to: 'errors#exception_occured', via: :all



	resources :rides  do 
     collection  do  
        get 'previous_rides' 
     end
  end 
  
resources :rides  do 
     collection  do  
        get 'archive_rides' 
     end
  end 

  # resources :users  do 
  #    collection  do  
  #       get 'verify_uid'
  #    end
  # end 
  get '*unmatched_route', :to => 'application#raise_not_found!'
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :from_user, class_name: "User"

  validates :star, presence: true
  validates :comment, length: { minimum: 5 }

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_rating, only: [ :edit, :update, :destroy]
  # before_filter :show_ratings
  
  def hints
    puts params
  end
  def rate_user
    @user = User.find(current_user.message_threads.find(params[:thread_id]).communicator_id)
    if @user.present?
        rating = @user.ratings.find_by(from_user_id: current_user.id)
        if rating.present? 
          redirect_to edit_rating_path(rating.id)
        else
          redirect_to new_rating_path({ uid: @user.id})
        end
    else
      flash[:danger] = "Sorry! This information does not belong to a LaMule member."
      redirect_to hints_ratings_path
    end
  end
  def search_user
    if current_user.email == params[:email ] || current_user.phone_number.body == params[:phone_no] || current_user.phone_number.body == "0#{params[:phone_no]}"
      flash[:danger] = "You can't leave yourself a rating!"
      redirect_to hints_ratings_path
    else

      if params[:email].present?
        @user = User.find_by(email: params[:email])
      elsif params[:phone_no].present?
        
        if params[:phone_no][0] == "0"
          params[:phone_no].slice!(0)
        end  
        @user = User.joins(phone_number: :country).find_by("phone_numbers.body = ? AND countries.id = ?", params[:phone_no], params[:country_id])
      end
      
      if @user.present?
        rating = @user.ratings.find_by(from_user_id: current_user.id)
        if rating.present? 
          redirect_to edit_rating_path(rating.id)
        else
          redirect_to new_rating_path({ uid: @user.id})
        end
      else
        flash[:danger] = "Sorry! This information does not belong to a LaMule member."
        redirect_to hints_ratings_path
      end
    end
    

  end

  def received
    show_ratings(current_user)
  end

  def given
    @ratings = current_user.given_ratings
  end

  def new
    @user = User.find(params[:uid])
    @rating = current_user.given_ratings.new(user_id: @user.id)
  end

  def create
    @rating = current_user.given_ratings.build(rating_params)
    if @rating.save
      user = User.find(params[:rating][:user_id])
      if user.notifications.notification_status('receive_rating')
        puts 'ratingmailsent_real'
        mandrill = MandrillMailer.new
        mandrill.rating_recieved_mail(user)
      end
      redirect_to given_ratings_path
    else
      @user = User.find(params[:rating][:user_id])
      render 'new'
    end
  end

  def edit
    @user = @rating.user
  end

  def update
    if @rating.update(rating_params)
      redirect_to given_ratings_path
    else
      render 'edit'
    end
  end

  def destroy
    @rating.destroy
    redirect_to given_ratings_path
  end

  private
  def set_rating
    @rating = current_user.given_ratings.find(params[:id]) 
  end

  def rating_params
    params.require(:rating).permit(:user_id, :star, :comment, :driving_skill, :user_type)
  end

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<script type="text/javascript">
  var max_char = 200;
  $(document).ready(function () {
    remaing_comment_char( $("#rating_comment") );
    $('.star-rating').raty({
      mouseout: function (score, evt) {
        if ($('#hint').text() == "") {
          $('#hint').text("0");
        }
      },
      hints: ['1', '2', '3', '4', '5'],
      click: function (score, evt) {
        $('#rating_star').val(score);
      },
      score: function () {
        return $(this).attr('data-score');
      },
      targetKeep: true,
      target: "#hint"
    });
    $("#rating_comment").keydown(function(e){
      $(this).remaing_comment_char();
    });
    $("#rating_comment").keypress(function(e) {
      if (this.value.length > 199){
        e.preventDefault();
      }
  
  
    });
    $('.rating_user_type_radio').click(function(){
      if ($(this).val() ==  "driver"){
        $(".user-rate-div").removeClass("hidden");
        $(".user-skill-div").removeClass("hidden");
      }else{
        $(".user-rate-div").removeClass("hidden");
        $(".user-skill-div").addClass("hidden");
      }
  
    });
  });
  function remaing_comment_char($this){
  var remaining_char = max_char - $this.val().length;
  $(".char_count_remain").text(remaining_char);
  }
</script>
<%= hidden_field_tag "active-side-nav-link", "hints" %>

<div class="offer_ride booking profile">
  <div class="col-md-10 col-sm-12 col-xs-12">
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- leave_rating start -->
      <div role="tabpanel" class="tab-pane active change_password " id="leave_rating">
        <div class="panel panel-default">
          <div class="panel-heading">Rating
          </div>
          <div class="panel-body m-15">
            <%= form_for @rating, html: { multipart: true } do |f| %>
              <div class="col-md-12">
                <div class="row">
                  <div class="col-md-7">
                    <%= f.hidden_field :user_id, value: @user.id %>
                    <div class="radio">
                      <%= f.radio_button :user_type, :passenger, class: "" %>
                      <%= label :user_type_passenger, "a passenger " %>
                    </div>
                    <div class="radio">
                      <%= f.radio_button :user_type, :driver, class: "" %>
                      <%= label :user_type_driver, "a driver during the trip" %>
                    </div>
                    <div class="radio">
                      <%= f.radio_button :user_type, :unknown, class: "" %>
                      <%= label :user_type_unknown, "I did not travel with #{@user.display_first_last_name}" %>
                    </div>
                  </div>
                  <div class="col-md-5 pic_area">
                    <div class="user_profile text-center">
                      <div class="img_holder">
                        <a href="<%= public_profile_user_path(@user.id) %>"><img src="<%= avatar_url @user %>" class="img-responsive" alt="<%= @user.display_first_last_name %>"></a>
                        <span class="tag"><i class="fa fa-star"></i>
                          <%= @user.calculated_rating %>
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="rating_comments">
                    <div class="col-md-12 row">
                      <p>Click the stars with 1 being not good & 5 being awesome</p>
                      <div class=" rating_list">
                        <ul>
                          
                          <span class="star-rating" data-score="<%= @rating.star %>"></span>
                          <span><span id="hint"></span> star(s) </span>
                          <%= handle_error_text(@rating, :star) %>
                          <%= f.hidden_field :star %>
                        </ul>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label for="exampleInputEmail5">Some quick Comments</label>
                          <%= handle_error_text(@rating, :comment) %>
                          <%= f.text_area :comment, placeholder: "How was your car share (on time, pleasant, fun, etc.)? Do you recommend this member to the community?", class: "form-control text_box", rows: 4 %>
                          <!-- <textarea class="form-control text_box" placeholder="Max 500 Charecters " rows="3" id="exampleInputEmail5"></textarea> -->
                        </div>
                      </div>
                      <div class="col-md-12 btn_block text-center btn_change">
                        <%= f.submit "PUBLISH", class: "pull-right b_25 color btn_offer btn btn-default btn-sm navbar_ride_btn" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <!-- leave_rating end -->
    </div>
  </div>
</div>

app/views/ratings/_show_driver_rating.html.erb
<% @rating = user.ratings %>
<% if @rating.present? %>
<span>
  <%= image_tag 'rating/star-on.png', class: "inline-block", style: "margin-top: -4px;" %>
  
  <%= "#{(@rating.pluck('star').sum.to_f/@rating.count).round(2)} - #{@rating.count} ratings" %>
  <br>
  <% if calculate_rank(user)!="newcomer" %>
  Ranking :  <%= calculate_rank(user) %>
  <% end %>

</span>
<% end %>

app/views/ratings/edit.html.erb
<%= render 'form' %>

app/views/ratings/given.html.erb
<script type="text/javascript">
  $(document).ready(function () {
    var max_char = 200;
    $('.star-rating').raty({
      readOnly: true,
      hints: ['1', '2', '3', '4', '5'],
      score: function () {
        return $(this).attr('data-score');
      },
    });

  });

</script>
<%= hidden_field_tag "active-side-nav-link", "given" %>
<div class="offer_ride booking profile">
  <div class="col-md-10 col-sm-12 col-xs-12">
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- rating_given end -->
      <div role="tabpanel" class="tab-pane  active rating_given" id="rating_given">
        <div class="panel panel-default">
          <div class="panel-heading">Rating given
          </div>
          <div class="panel-body m-15">
            <% if @ratings.present? %>
              <% @ratings.each do |rating| %>
                <div class="col-md-12">
                  <div class="passenger-block">
                    <div class="passenger-holder">
                      <div class="col-md-3 col-sm-4 col-xs-12">
                        <div class="image-holder">
                          <img src="<%= avatar_url rating.user %>" class="img-responsive" alt="">
                        </div>
                      </div>
                      <div class="passenger-textarea col-md-9 col-sm-8 col-xs-12">
                        <h4 ><%= rating.user.display_first_last_name %></h4>
                        <div class=" rating_list ">
                            <span class="star-rating" data-score="<%= rating.star %>"></span>
                        </div>
                        <div class="clearfix"></div>
                        <span><%= date_in_today_format(rating.updated_at) %></span>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <P><%= rating.comment %></P>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h4>No rating given</h4>
            <% end %>
          </div>
        </div>
      </div>
      <!-- rating_given end -->
    </div>
  </div>
</div>












<div class="well hidden">
  <% if @ratings.present? %>
    <h4><%= current_user.given_ratings.count %> rating given</h4>
    <ul class="list-left-advices unstyled clearfix">

      <% @ratings.each do |rating| %>
        <% @user = rating.user %>
        <li>
          <div class="left-advice-container clearfix">
            <div class="left-advice-header">
              <span class="pull-right"><%= date_in_today_format(rating.updated_at) %></span>
              <% if rating.user.present? %>
                <a href="<%= public_profile_user_path(rating.user.id) %>" class="inline-block">
                  <%= image_tag @user.profile.picture('inbox_thumb'), class: 'user-picture tip inline-block', alt: "#{@user.display_first_last_name} (#{@user.age})", width: "54", height: "54", style: "width: 54px; height: 54px;" %>
                </a>
              <% end %>
              <h4>Rating : <%= rating.star %> / 5</h4>
              <span class="star-rating" data-score="<%= rating.star %>"></span>
            </div>
            <% if @user.present? %>
              <p><strong>For <%= @user.display_first_last_name %>:</strong> <%= rating.comment %></p>
            <% end %>
            <%= link_to "edit", edit_rating_path(rating.id), class: 'btn btn-mini btn-primary' %>
            <%= link_to t('.destroy', default: t("helpers.links.destroy")), rating_path(rating.id), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger' %>
          </div>

        </li>

        <br/>
      <% end %>
    </ul>
  <% else %>
    <h4>No rating given</h4>
  <% end %>

</div>

app/views/ratings/hints.html.erb
<%= hidden_field_tag "active-side-nav-link", "hints" %>
<div class="offer_ride booking profile">
  <div class="col-md-10 col-sm-12 col-xs-12">
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- leave_rating start -->
      <div role="tabpanel" class="tab-pane active change_password " id="leave_rating">
        <div class="panel panel-default">
          <div class="panel-heading">Rating
          </div>
          <div class="panel-body m-15">
            <div class="col-md-12">
              <h4>Leave a rating for another member</h4>
              <p>Find a member using their phone number or email address to leave a rating for.</p>
              <%= form_tag search_user_ratings_path, method: :get, role: "form" do %>
              <div class="row">
                <div class="col-sm-8">
                  <div class="form-group">
                    <label for="email">Email</label>
                    <%= email_field_tag :email, nil, class: "email_box form-control", placeholder: "Email" %>
                    <%= number_field_tag :phone_no, nil, placeholder: 'Phone', class: "form-control hidden" %>
                  </div>
                </div>
                <div class="col-sm-4 col-xs-12 btn_block text-center btn_change">
                  <%= submit_tag "FIND", name: nil, class: "b_25 color btn_offer btn btn-default btn-sm  navbar_ride_btn" %>
                </div>
              </div>
              <% end %>
              <%= form_tag search_user_ratings_path, method: :get, role: "form" do %>
              <div class="row">
                <div class="col-sm-8">
                  <div class="form-group">
                    <label for="exampleInputEmail3">Phone</label>
                    <%= email_field_tag :email, nil, class: "email_box form-control hidden", placeholder: "Email here" %>
                    <%= number_field_tag :phone_no, nil, placeholder: 'Phone', class: "form-control" %>
                  </div>
                </div>
                <div class="col-sm-4 col-xs-12 btn_block text-center btn_change">
                  <%= submit_tag "FIND", name: nil, class: "b_25 color btn_offer btn btn-default btn-sm  navbar_ride_btn" %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- leave_rating end -->
      <!-- rating_received start -->
      <div role="tabpanel" class="tab-pane transaction change_password personal_info" id="rating_received">
        <div class="panel panel-default">
          <ul role="tablist" class="nav nav-tabs">
            <li class="active" role="presentation"><a data-toggle="tab" role="tab" aria-controls="home" href="#home" aria-expanded="true">Driver</a></li>
            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="profile" href="#profile" aria-expanded="true">Passenger</a></li>
            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="profile" href="#messages" aria-expanded="true">Anonymous</a></li>
          </ul>
          <div class="panel-body">
            <div class="tab-content">
              <div id="home" class="tab-pane active" role="tabpanel">
                <div class="row">
                  <div class="col-md-6 col-xs-6 col-xs-12">
                    <h4>some text here</h4>
                    <p>some text here some text here</p>
                  </div>
                  <div class="col-md-6 col-xs-6 col-xs-12 rating_list">
                    <ul>
                      <li><a href="#"><i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <span>5</span></a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-md-12">
                    <div class="driver_rate">
                      <div class="passenger-block ">
                        <div class="passenger-holder">
                          <div class="col-md-6 col-sm-4 col-xs-12">
                            <div class="image-holder">
                              <img src="/assets/user/icon-man-108.png" class="img-responsive" alt="">
                            </div>
                          </div>
                          <div class="passenger-textarea col-md-4 col-sm-8 col-xs-12">
                            <h4 class="pull-left">Jake Smith</h4>
                            <div class="clearfix"></div>
                            <span>Date : 11/07/2015</span>
                            <div class=" rating_list ">
                              <ul>
                                <li><a href="#"><i class="fa fa-star"></i>
                                  <i class="fa fa-star"></i>
                                  <i class="fa fa-star"></i>
                                  <i class="fa fa-star"></i>
                                  <i class="fa fa-star"></i>
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-12">
                          <p>Jake was a great passenger bla bla bla</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- rating_given end -->
      <div role="tabpanel" class="tab-pane  change_password personal_info rating_given" id="rating_given">
        <div class="panel panel-default">
          <div class="panel-heading">Rating given
          </div>
          <div class="panel-body ">
            <div class="col-md-12">
              <div class="passenger-block">
                <div class="passenger-holder">
                  <div class="col-md-3 col-sm-4 col-xs-12">
                    <div class="image-holder">
                      <img src="/assets/user/icon-man-108.png" class="img-responsive" alt="">
                    </div>
                  </div>
                  <div class="passenger-textarea col-md-9 col-sm-8 col-xs-12">
                    <h4 class="pull-left">Jake Smith</h4>
                    <div class=" rating_list pull-right">
                      <ul>
                        <li><a href="#"><i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                    <div class="clearfix"></div>
                    <span>Date : 11/07/2015</span>
                  </div>
                </div>
                <div class="col-md-12">
                  <P>Jake was a great passenger bla bla bla</P>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- rating_given end -->
      <div role="tabpanel" class="tab-pane  change_password personal_info" id="rating_given">
        <div class="panel panel-default">
          <div class="panel-heading">My Persssonal information
          </div>
          <div class="panel-body ">
            <div class="col-md-12">
              bdfknsdnfsdk
            </div>
          </div>
        </div>
      </div>
      <!-- rating_given end -->
    </div>
  </div>
</div>
<% flash.each do |name, msg| %>
<%# if msg.is_a?(String) %>
<%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
<%# end %>
<% end %>

app/views/ratings/new.html.erb
<%= render 'form' %>

app/views/ratings/received.html.erb
<%= hidden_field_tag "active-side-nav-link", "received" %>
<% @user = current_user %>
<%= render :partial => 'show_ratings', :profile_user => current_user %>