config/routes.rb
Rails.application.routes.draw do
  get 'errors/exception_occured'

	get '/analytics', to: "analytics#index"
	get 'messages/received'
	get 'messages/sent'
	get 'messages/archived'
	get 'dashboard/show_dashboard'
	get 'dashboard/contact_us'
	get 'dashboard/contact_us_submit'
	get 'dashboard/public_urls'
	get 'summary/Lamule_community'
	get 'summary/ExperienceLevel'
	get 'summary/history'
	get 'summary/policy'
	get 'summary/partner'
	get 'summary/termsconditions'
	get 'summary/howitworks'
	get 'summary/origin'
	get 'summary/about_us'
	get 'users/index_facebook'
	get 'users/index_not_facebook'
	get 'users/signUp_email_page'
	post 'users/verify_uid'
	get 'transections/payment'
	get 'driver_verifications/profile_verification'
	get 'driver_verifications/personal_information'
	post 'transfer_requests/make_transfer_request'


	get 'driver_verifications/email_token_generator'
	
	post 'transfers/transfer_funds'
	get 'notifications/booking_notifications'
	match '/twitter', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-blog-post', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-shark-tank', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-inspirational', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-add', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/fb-boosted-post', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/instagram', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/edm', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/press', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/news', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/photopostcards', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/unirideshare', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/alpinerideshare', :to => 'dashboard#public_urls', :via => [:get, :post]
	match '/surfrideshare', :to => 'dashboard#public_urls', :via => [:get, :post]
	


	devise_for :users,
						 controllers: {
								 sessions: "users/sessions",
								 registrations: "users/registrations",
								 passwords: "users/passwords",
								 omniauth_callbacks: "users/omniauth_callbacks"
						 }
	root :to => "dashboard#index"
	resources :users

	get "/fill_phone", to: "phone_number#fill_phone"
	get "/verify_phone_number", to: "phone_number#verify_phone_number"
	get "/confirm_phone", to: "phone_number#confirm_phone"
	get "/confirmation_phone", to: "phone_number#confirmation_phone"
	get "/complete_registration_proccess", to: "users#complete_registration_proccess"
	get "/send_verify_email", to: "users#send_verify_email"
	get "/verified_the_email", to: "users#verified_the_email"
	get "/profile/preferences", to: "preferences#edit"
	get "/profile/notifications", to: "notifications#index"
	get "/profile/social_sharing", to: "users#social_sharing"
	get '/profile/credit_card', to: "users#credit_card"
	post '/transfers/revert_transfer/:id', to: "transfers#revert_transfer", as: "revert_transfer"
	patch '/profile/update_credit_card_info', to: "users#update_credit_card_info"
	post "/profile/disconnect_facebook", to: "users#disconnect_facebook"
	
	get "/offer-seats/1", to: "rides#offer_seat_1"
	get "/:id/offer-seats/2", to: "rides#offer_seat_2"
	resources :users, only: [] do
		member do
			get :public_profile
			get :payments_history
		end
		collection do
			post :send_direct_message
		end	
	end
	
	resources :driver_verifications, only: [:index] do
		collection do
			get :steps
			post :verify_profile
			post :verify_email_pin_code
			post :verify_phone_pin_code
			get  :check_email_verified
			get  :check_phone_verified
			post :verify_personal_info
			get :finished
		end	
	end
		
	resources :bookings do
		collection do
			get :past_bookings
		end
		member do
			get :accept
			get :reject
		end
	end
	resources :profile, only: [] do
		collection do
			get :general
			get :photo
			get :verifications
			get :address
			patch :update_general_info
			patch :update_address
			post :verify_email_phone
		end
		member do
			patch :upload_photo
		end
	end
	resources :unsubscribes, only: [] do
		collection do
			get 'account'
			delete 'delete_account'
		end
	end
	resources :cars, only: [:index, :new, :create, :edit, :update, :destroy] do
		member do
			patch :upload_image
		end
	end

	resources :transections, only: [:refund] do
		member do
			get :refund
		end
	end
	
	resources :car_makers, only: [] do
		resources :car_models, only: [:index]
	end
	resources :preferences, only: [:update]
	resources :notifications, only: [] do
		collection do
			patch :update_user_notifications
			patch :update_fackbook_notifications
		end
	end
	resources :rides, only: [:index, :destroy, :edit, :update, :show, :create] do
		resources :locations, only: [:destroy]
		collection do
			post :create_offer_1
			get :rides_info
			post :make_legs
			post :make_schedule
			get :previous_rides
			get :archive_rides
			get :range_rides
		end
		member do
			get :share_on_facebook
			patch :create_offer_2
			get :publication
			patch :set_car
			get :contact_to_the_driver
			put :add_seat
			put :delete_seat
			post :duplicate_ride
			get :visitors
			patch :archive
			get :successfully_posted_rides
		end
	end

	resources :message_threads, only: [:show, :destroy] do
		resources :messages, only: [:create]
		member do
			post :set_archive
		end
	end

	resources :ratings, only: [:new, :create, :edit, :update, :destroy] do
		collection do
			get :hints
			get :search_user
			get :rate_user
			get :received
			get :given
		end
	end

	resources :email_alerts, only: [:index, :new, :create, :destroy] do
		collection do
			get :send_email
			get :email_cron
		end
		member do
		   get :update_travel_date
		end
	end

	resource :mail_chimp, only: [:create]

	match '/404', to: 'errors#exception_occured', via: :all
	match '/422', to: 'errors#exception_occured', via: :all
	match '/500', to: 'errors#exception_occured', via: :all



	resources :rides  do 
     collection  do  
        get 'previous_rides' 
     end
  end 
  
resources :rides  do 
     collection  do  
        get 'archive_rides' 
     end
  end 

  # resources :users  do 
  #    collection  do  
  #       get 'verify_uid'
  #    end
  # end 
  get '*unmatched_route', :to => 'application#raise_not_found!'
end

app/models/driver_verification.rb
class DriverVerification < ActiveRecord::Base
  belongs_to :user
  attr_accessor :f_name, :l_name, :email, :p_num, :pin_email, :pin_mobile,:update_email,
                :car_image, :car_model, :car_make, :car_state, :post_code, :post_address, :avatar
 # validates :pin_email, presence: true                
  # tokenify!(:email_token)
end

app/controllers/driver_verifications_controller.rb
class DriverVerificationsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_header
	before_action :set_mobile_header_flag, :only => [:finished,:steps]
	before_action :set_message_icon_flag, :only => [:finished,:steps]
	before_action :set_duplicate_email_flag, :only => [:email_token_generator]
	before_action :activate_wizard_nav, except: [:index]

	layout 'driver_verification', except: [:index]

	def index
	end
	
	def set_mobile_header_flag
		@mobile_header_flage = true
	end

	def steps
		@verify = DriverVerification.new
		@verify.f_name = current_user.first_name
		@verify.l_name = current_user.last_name
		@verify.email = current_user.email
		if current_user.cars.present?
			@verify.car_make = current_user.cars.first.car_maker.id
			@verify.car_image = current_user.cars.first.car_image
			@verify.car_model = current_user.cars.first.car_maker.car_models.first.name 
			@car = current_user.cars.first
		else	
			@verify.car_make = CarMaker.first.id
			@verify.car_image = 'upload_img.png'
			@verify.car_model = CarMaker.first.car_models.first.name
			@car = current_user.cars.create
			@car.car_maker_id = CarMaker.first.id
			@car.save
		end
		if current_user.profile.present?
			@verify.post_code = current_user.profile.postcode
			@verify.post_address = current_user.profile.address_1
			@verify.avatar = current_user.profile.picture
		else	
			@verify.avatar = 'user/icon-man-72.png'
			@verify.post_code = nil
			@verify.post_address = nil
		end	
   		@final_step = current_user.driver_verification.verified if current_user.driver_verification.present?
	end	

	def finished

	end

	def profile
		@verify = DriverVerification.new
		@user = current_user
	end

	def personal
		@user = current_user
		@car = current_user.cars.first
	end	

	def verify_personal_info
		if params[:pin_email] != "" && params[:pin_mobile] != ""
			if current_user.driver_verification.email_token == params[:driver_verification][:pin_email] || current_user.verified_credentials
				current_user.phone_number.update!(verified_no: true)
				current_user.update!(email_verified: true, verified_credentials: true)
				current_user.update(email: params[:driver_verification][:update_email]) 
				current_user.cars.first.update_car_info(params[:driver_verification][:car_model], params[:driver_verification][:car_make], params[:driver_verification][:car_image].present? ? params[:driver_verification][:car_image] : nil) if current_user.cars.present?
				current_user.profile.update_verification_information(params[:driver_verification][:post_code],params[:driver_verification][:post_address], params[:driver_verification][:avatar].present? ? params[:driver_verification][:avatar] :nil ) if current_user.profile.present?
				current_user.driver_verification.update_attributes(verified: true)
				redirect_to finished_driver_verifications_path
			else
				redirect_to steps_driver_verifications_path
			end	
		else
			redirect_to steps_driver_verifications_path
		end
	end	

	def email_token_generator	
	 	email = params[:email]
		driver_ver = current_user.driver_verification
		if @duplicate_email_flag == false
			token = CodeGenerator::Generator.generate(uniqueness: { model: :driver_verification, field: :email_token })
			driver_ver.email_token = token
			if driver_ver.save
				send_verification_email(token, email, current_user.first_name)
				respond_to do |format|
				format.json { render :json => { success: true },:flash => {:notice => 'An email has been sent with the verification pin.' }}
				format.html {redirect_to :back, :flash => {:notice => 'An email has been sent with the verification pin.' }}
				end 
			end			
		else
			respond_to do |format|
				format.js {  flash.now[:notice] = 'This email is already connected to another user' }
				format.json { render :json => { :success => false }}
			end	
		end
	end 
	
	def set_duplicate_email_flag
		email = params[:email]
		@duplicate_email_flag = false
		if current_user.email == email
			@duplicate_email_flag = false
		else
			@duplicate_email_flag = User.where(email: email).present?
		end
	end

	def verify_email_pin_code
		 if current_user.driver_verification.email_token == params[:email_pin]
			respond_to do |format|
				format.json { render :json => {:success => true}}
			end
		else
			respond_to do |format|
			format.js {  flash.now[:notice] = "Wrong PinCode" }
	    	format.json { render :json => {:success => false}}
			end
		end
	end
	
	def verify_phone_pin_code
		if current_user.phone_number.verification_code.to_s == params[:phone_pin]
			respond_to do |format|
				format.json { render :json => {:success => true}}
			end
		else
			respond_to do |format|
				format.js {  flash.now[:notice] = "Wrong PinCode" }
	    	format.json { render :json => {:success => false}}
			end
		end
	end

	def check_email_verified
		if current_user.email_verified == true
			respond_to do |format|
			format.json { render :json => {:success => true}}
			end
		else
			respond_to do |format|
			format.json { render :json => {:success => false}}
			end
		end
	end


	def check_phone_verified
		if current_user.phone_number.verified_no == true
			respond_to do |format|
			format.json { render :json => {:success => true}}
			end
		else
			respond_to do |format|
			format.json { render :json => {:success => false}}
			end
		end
	end

	private
		def send_verification_email(code, email, first_name)
		 mail_obj = MandrillMailer.new
		 mail_obj.driver_verification(code, email, first_name)
		end

		def verification_params
			params.require(:driver_verification).permit!
		end

		def activate_wizard_nav
			@wizard_nav = true
		end
end

app/helpers/driver_verifications_helper.rb
module DriverVerificationsHelper

  def verification_final_step(step)
    if step == true
      return "active"
    end  
  end  

  def final_verification_tab(step)
    if step == true
      return "active"
    else 
      return ""  
    end  
  end  

  def non_final_verification_tab(step)
    if step == false
      return "active"
    else 
      return ""  
    end  
  end 

end

app/views/driver_verifications/email_token_generator.js.erb
$("#flash").html('<%= j render partial: "layouts/flash_messages" %>');

app/views/driver_verifications/finished.html.erb
<%= render 'layouts/navigation_2_links' %>
<div class="container driver_details ">
  <div id="rootwizard">   
    <div class="form_area">
        <div class="tab-pane active" id="tab3">
          <div class="container">
            <div class="trust_drive text-center thank_you">
              <div class="col-md-offset-4 col-md-4  centered">
                <div class="image_holder">
                  <%= image_tag 'Silly_icon.png', class: 'img-responsive'%>
                </div>
                <h1>Thank you!</h1>
                <p>You are now a verified driver. You can now go ahead and post a ride!
                </p>
                <!-- <P>In the meantime you can create a ride which will
                  be publicly shown once your profile is verified.
                </P> --> 
                <a class="btn btn-default active btn_green b_25" href="/offer-seats/1" role="button">POST RIDE</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/driver_verifications/index.html.erb
<div class="container">
  <div class="trust_drive text-center">
    <div class="col-md-offset-3 col-md-6  centered">
    <div class="image_holder">
    	<%= image_tag 'Wild_icon.png', class: 'img-responsive'%>
     </div>
    <h1>Become a trusted driver.</h1>
    	<div class="text-holder">
    		<p>Becoming a driver is 100% free of charge. Save some money
from your trips and contribute to a
greener community.</p>
    	</div>
    <a class="btn btn-default active b_25" href="<%= steps_driver_verifications_path %>" role="button">JOIN NOW</a>
</div>

app/views/driver_verifications/personal.html.erb
  <div class="container driver_details ">
  <div id="rootwizard">
  <% @step = 2 %>
  <%= render 'driver_verifications/partials/wizard_nav', step: @step%>
    <div class="form_area">
        <div class="col-md-8 col-md-offset-2">
          <div class="driver_details">
            <h4>Vehicle</h4>
            <div class="row">
            <%= form_tag verify_personal_info_driver_verification_path(@user)  do %>
              <div class="col-md-6 col-sm-6 ">
                <div class="box">
                  <div class="img_holder">
                    <% if @car.car_image.present? %>
                      <%= image_tag @car.car_image, class: 'img-responsive', id: 'car_image_upload_preview'%>
                    <% else %>  
                      <%= image_tag 'upload_img.png', class: 'img-responsive', id: 'car_image_upload_preview'%>
                    <% end %>
                  </div>
                  <span class="btn btn-link fileinput-button">
                    <span><strong>Change profile image</strong></span>
                    <%= file_field_tag :photo, id:'inputFilecar' %>
                  </span>
                </div>
              </div>
              <div class="col-md-6 col-sm-6 form_box">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Make</label>
                    <!-- <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value=""> -->
                    <%= text_field_tag :make,@car.car_maker.name,class: 'form-control'%>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Model</label>
                    <!-- <input type="text" class="form-control" id="exampleInputPassword1" placeholder=""> -->
                    <%= text_field_tag :model,@car.car_model.name,class: 'form-control'%>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Sate the car is registered in</label>
                    <!-- <input type="text" class="form-control" id="exampleInputPassword1" placeholder=""> -->
                    <%= text_field_tag :state,nil,class: 'form-control'%>
                  </div>
              </div>
              <div class="clearfix"></div>
              <hr>
              <div class="profile_img_area">
                <div class="col-md-12">
                  <h4>Profile image and postcode</h4>
                  <div class="col-md-4 col-sm-6 text-center">
                    <div class="img_holder upload-preview">
                      <%= image_tag current_user.profile.picture, class: 'img-responsive', id: 'image_upload_preview'%>
                    </div>
                    <!-- <a href="#">Change profile image</a> -->
                    <span class="btn btn-link fileinput-button">
                    <span><strong>Change profile image</strong></span>
                    <%= file_field_tag :photo, id:'inputFile' %>
                    </span>
                  </div>
                  <div class="col-md-6 col-sm-6 ">
                      <div class="form-group">
                        <label for="exampleInputPassword1">Your Postcode</label>
                        <!-- <input type="text" class="form-control" id="exampleInputPassword1" placeholder=""> -->
                        <%= text_field_tag :postcode,current_user.profile.postcode,class: 'form-control'%>
                      </div>
                      <div class="form-group">
                        <h4>Postal address (This is Kept private)</h4>
                        <!-- <input type="text" class="form-control" id="exampleInputPassword1" placeholder=""> -->
                        <%= text_field_tag :address_1,current_user.profile.address_1,class: 'form-control'%>
                        <small>When you enter your postal address we will send you a bumper sticker</small>
                      </div>
                  </div>
                </div>
              </div>
              <hr>
              <div class="payment_account">
                <div class="col-md-12">
                  <p>Insert Payment Account set up Here</p>
                </div>
              </div>
              <div class="col-md-12">
                <!-- <a class="btn btn-large btn_next pull-right" href="#tab3" data-toggle="tab">Continue</a> -->
                <%= submit_tag 'Continue', class: 'btn btn-large btn_next pull-right'%>
              </div>
              <% end %>
            </div>
          </div>
        </div>
    </div>
   </div>
   </div>

<script>
  $(document).ready(function() {
   alert("hey");
  });
</script>

app/views/driver_verifications/personal_information.html.erb
<!-- Load the Facebook JavaScript SDK -->  
    <div id="fb-root"></div>
    <script src="//connect.facebook.net/en_US/all.js"></script>    
    <script type="text/javascript">
   // $(document).ready(function(){
      
      // Initialize the Facebook JavaScript SDK
      FB.init({
        appId: '562756200542819',
        xfbml: true,
        status: true,
        cookie: true,
      });
      
      // Check if the current user is logged in and has authorized the app
      //FB.getLoginStatus(checkLoginStatus);      
      // Login in the current user via Facebook and ask for email permission
      function authUser() {
        FB.login(checkLoginStatus, {scope:'email'});
      }     
      // Check the result of the user status and display login button if necessary
      function checkLoginStatus(response) {
        if(response && response.status == 'connected') {
                  
           var uid = response.authResponse.userID;
           var accessToken = response.authResponse.accessToken;  
           $.ajax({
            type: 'POST',        
            data: {fb_id:uid},
            url: '/users/verify_uid',
            success: function(data) {
//              console.log(data.success);
              FB.api('/me', function(response) {                        
        //      console.log(response);
              if(data.success==true)
              {
                alert('User is authorized');
                var elem = document.getElementById("exampleInputEmail1");
                elem.value = response.first_name;
                elem = document.getElementById("exampleInputEmail2");
                elem.value = response.last_name;
                elem = document.getElementById("verified_email");
                elem.value = response.email;
                var code_email=document.getElementById("email_code_send");
                code_email.value=elem.value;


              }
              if(data.success==false)
              {
                alert('Facebook ID already linked');      
              }

              });

            },
            error: function(){
            //  console.log('error!');
            }
        });

       
          // Hide the login button
         // document.getElementById('loginButton').style.display = 'none';
          
          // Now Personalize the User Experience
          // console.log('User ID: ' + uid);
          // console.log('Access Token: ' + accessToken);

        } else if (response.status === 'not_authorized') {

            alert('User logged into Facebook, but not your app');

      // The person is logged into Facebook, but not your app.
           // document.getElementById('status').innerHTML = 'Please log ' +
            //  'into this app.';
          
          } else {

            alert('User not logged into Facebook, no on app');

            // The person is not logged into Facebook, so we're not sure if
            // they are logged into this app or not.
           // document.getElementById('status').innerHTML = 'Please log ' +
            //  'into Facebook.';
          
          }
      }



      function sendCode() {
        alert('in send code func');  
        var mail = document.getElementById("email_code_send").value;
        $.ajax({

            type: 'GET',
          data: {fb_email:mail},       
            url: '/driver_verifications/email_token_generator',
            success: function(data) {
              
           //   console.log(data.success);              
            },
            error: function(){
          //    console.log('error!');
            }
        });



      }

//});
    </script>
    

<div class="container driver_details ">
<div id="rootwizard">
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <ul>
        <li  class="active"><a href="#tab1" data-toggle="tab">Verify Your Profile</a></li>
        <li><a href="#tab2" data-toggle="tab">Personal details and car</a></li>
        <li><a href="#tab3" data-toggle="tab">Done</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="form_area">
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <div class="title_msg text-center">
        your data is safely encrypted and transferred via 256-bit security.
      </div>
      <%= form_tag verify_personal_information_driver_verification_path(@user) do %>
      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <div class="">
          <div class="fascebook_btn">
            <label>Confirm your ID</label>
            <div class="input-group">
              <button type="button" id="loginButton"  onclick="authUser();" class="btn  btn-lg"><i class="fa fa-facebook"></i> CONNECT FASCEBOOK</button>
            </div>
          </div>
          <div class="col-sm-6 form_box">
            <h4></h4>
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">First Name</label>
                <input type="text" placeholder="" id="exampleInputEmail1" class="form-control">
              </div>
            </form>
          </div>
          <div class="col-sm-6 form_box">
            <h4></h4>
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Last Name</label>
                <input type="text" placeholder="" id="exampleInputEmail2" class="form-control">
              </div>
            </form>
          </div>
          <div class="col-md-12">
            <div class="email">
              <div class="form-group">
                <label>Email</label>
                <div class="input-group">
                  <input type="text" class="form-control" id="verified_email" placeholder="Your current verified email address is sam@getyper.io" />
                </div>
              </div>
            </div>
            <div class="form-group send_code">
              <label>Email Address</label>
              <div class="input-group">
                <input type="text" class="form-control" id="email_code_send" placeholder="+66" />
                <span class=" input-group-btn">
                  <button class="btn btn-default" type="button" id="send_code" onclick="sendCode();">SEND CODE</button>
                </span>
                
              </div>
            </div>
            <div class="form-group send_code">
              <label>Phone number</label>
              <div class="input-group">
                <input type="text" class="form-control" placeholder="" />
                <span class=" input-group-btn">
                  <button class="btn btn-default"  type="button">SEND CODE</button>
                </span>
              </div>
            </div>
            <div class="col-sm-6 form_box">
              <h4></h4>
              <form>
                <div class="form-group">
                  <label for="exampleInputEmail1">First Name</label>
                  <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Your 4 digit pin">
                </div>
              </form>
            </div>
            <div class="col-sm-6 form_box">
              <h4></h4>
              <form>
                <div class="form-group">
                  <label for="exampleInputEmail1">First Name</label>
                  <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Your 4 digit pin">
                </div>
              </form>
            </div>
            <!-- <a class="btn btn-large btn_next pull-right" a href="#tab2" data-toggle="tab">Continue</a>  -->
            <%= submit_tag 'Continue', class: 'btn btn-large btn_next pull-right'%>    
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/driver_verifications/profile_verification.html.erb
profile_verification

app/views/driver_verifications/verify_email_pin_code.js.erb
$("#flash").html('<%= j render partial: "layouts/flash_messages" %>');

app/views/driver_verifications/verify_phone_pin_code.js.erb
$("#flash").html('<%= j render partial: "layouts/flash_messages" %>');

app/views/driver_verifications/verify_profile.js.erb
//$("#notice").html("<%=j flash[:notice] %>");
console.log("yes");
$("#flash").html('<%= j render partial: "layouts/flash_messages" %>');